apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../mw
- deploy.yaml

configMapGenerator:
- name: wikibase-variables
  behavior: merge
  envs:
  - wikibase_extra.env
- name: extra-install
  files:
  - extra-install.sh

patchesJson6902:
- target:
    kind: Deployment
    name: wikibase-deployment
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/-
      value:
        name: quickstatements-data
        mountPath: /quickstatements/
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/-
      value:
        name: extra-install
        mountPath: /extra-install.sh
        subPath: entrypoint.sh
    - op: add
      path: /spec/template/spec/volumes/-
      value:
        name: quickstatements-data
        persistentVolumeClaim:
          claimName: quickstatements-data
    - op: add
      path: /spec/template/spec/volumes/-
      value:
        name: extra-install
        configMap:
          name: extra-install
