---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wikibase
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wikibase
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wdqs
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /q/(.*)
        pathType: Prefix
        backend:
          service:
            name: wdqs-frontend
            port:
              number: 8834
