---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wikibase
spec:
  rules:
  - host: wdqs.svc
  	# edit /etc/hosts on the browser machine
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wdqs-frontend
            port:
              number: 8834
  - host: quickstatements.svc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: quickstatements
            port:
              number: 8840
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wikibase
            port:
              number: 80
