---
apiVersion: v1
kind: Service
metadata:
  name: wikibase
spec:
  selector:
    app: wikibase
  ports:
   - protocol: TCP
     port: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wikibase-data
spec:
#  volumeName: wikibase-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikibase-deployment
  labels:
    app: wikibase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikibase
  template:
    metadata:
      labels:
        app: wikibase
    spec:
      initContainers:
      - name: create-shared
        image: wikibase/wikibase-bundle:1.36.3-wmde.5
        command: [ /bin/cp, "-an", "/var/www/html", /opt ]
        volumeMounts:
        - name: wikibase-data
          mountPath: /opt/html
        # This is why: https://docs.docker.com/storage/volumes/#populate-a-volume-using-a-container
      containers:
      - name: wikibase
        image: wikibase/wikibase-bundle:1.36.3-wmde.5
        envFrom:
        - configMapRef:
            name: wikibase-variables
        - secretRef:
            name: wikibase-variables
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wikibase-data
          mountPath: /var/www/html
      volumes:
      - name: wikibase-data
        persistentVolumeClaim:
          claimName: wikibase-data
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: wikibase-cron
spec:
  schedule: "33 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: wikibase-job
            image: wikibase/wikibase-bundle:1.36.3-wmde.5
            command:
              - /bin/bash
            args:
              - /entrypoint.sh
            env:
            - name: MAX_JOBS
              value: "1"
            envFrom:
            - configMapRef:
                name: wikibase-variables
            - secretRef:
                name: wikibase-variables
            volumeMounts:
            - name: wikibase-data
              mountPath: /var/www/html
              readOnly: true
            - name: entrypoint
              mountPath: /entrypoint.sh
              subPath: entrypoint.sh
          volumes:
          - name: wikibase-data
            persistentVolumeClaim:
              claimName: wikibase-data
          - name: entrypoint
            configMap:
              name: jobrunner-entrypoint

