resources:
- deploy.yaml

configMapGenerator:
- name: wikibase-variables
  envs:
  - wikibase.env
- name: jobrunner-entrypoint
  files:
  - entrypoint.sh=jobrunner-entrypoint.sh
- name: jobrunner-variables
  literals:
  - MAX_JOBS=1

secretGenerator:
- name: wikibase-variables
